version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-version:
      nodejs: 16
    commands:
      - echo "Installing dependencies..."
      - npm install

  test:
    commands:
      - echo "Running mocha"
      - mocha --exit

  post_build:
    commands:
      - echo "DONE!!"
